{{- if and (eq .Values.deployment.strategy "argo-rollouts") (eq .Values.deployment.rollouts.strategy "blueGreen") .Values.deployment.rollouts.blueGreen.previewIngress.enabled -}}
{{- $fullName := include "service-deployment.fullname" . -}}
{{- $previewServiceName := include "service-deployment.previewServiceName" . -}}
{{- $ingressPath := .Values.deployment.rollouts.blueGreen.previewIngress.path | default .Values.ingressInt.path -}}
{{- $ingressPathType := .Values.deployment.rollouts.blueGreen.previewIngress.pathType | default .Values.ingressInt.pathType -}}
{{- $ingressClass := .Values.deployment.rollouts.blueGreen.previewIngress.ingressClass | default .Values.ingressInt.ingressClass -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ .Release.Namespace }}-preview
  namespace: {{ .Values.deployment.rollouts.blueGreen.previewIngress.namespace | default .Release.Namespace }}
  {{- with .Values.deployment.rollouts.blueGreen.previewIngress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "service-deployment.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ $ingressClass }}
  {{- if .Values.deployment.rollouts.blueGreen.previewIngress.tls }}
  tls:
  {{- range .Values.deployment.rollouts.blueGreen.previewIngress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- if .Values.deployment.rollouts.blueGreen.previewIngress.hosts }}
  {{- range .Values.deployment.rollouts.blueGreen.previewIngress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: {{ $ingressPathType | default "Prefix" }}
            backend:
              service:
                name: {{ $previewServiceName }}
                port:
                  number: 80
  {{- end }}
  {{- else }}
    - http:
        paths:
          - path: {{ $ingressPath }}
            pathType: {{ $ingressPathType | default "Prefix" }}
            backend:
              service:
                name: {{ $previewServiceName }}
                port:
                  name: http
  {{- end }}
{{- end }}
